### ISSUE TITLE
grunt fails to run "wiredep" task

### ISSUE THREAD

**Issue by panev** [dgiormov/ista.agenda.builder.web#1]
Здравейте, 

Изглежда един от grunt тасковете търси bower.json в /app директорията, което спира serve. 

![image](https://cloud.githubusercontent.com/assets/3509489/4216693/82bab480-38dd-11e4-8ca5-7bfe9133ff15.png)

Дали някой ще може да погледне Gruntfile-а?

Благодаря,
Тодор

**Comment by fen4o** [comment]
Pull and try again

**Comment by fen4o** [comment]
You also want to use 57d78c9c78f8fb7404a697d77176e3326e72e6ae for mock data

**Comment by panev** [comment]
All is well now, thanks!
