### ISSUE TITLE
Session rating

### ISSUE THREAD

**Issue by panev** [dgiormov/ista.agenda.builder.web#10]
I've added the following markup to serve as the session-rating widget inside the sessiondetails view: 

```
<div class="rate-title">Enjoyed the Session?</div>
<ul class="rate-stars">
    <li class="rate-star yes-rated"><i class="fa fa-star"></i></li>
    <li class="rate-star yes-rated"><i class="fa fa-star"></i></li>
    <li class="rate-star yes-rated"><i class="fa fa-star"></i></li>
    <li class="rate-star yes-rated"><i class="fa fa-star"></i></li>
    <li class="rate-star not-rated"><i class="fa fa-star"></i></li>
</ul>
```

I've also styled it accordingly, when you add yes-rated/not-rated classes they stars get highlighted.

Please let me know if this would work for the session rating mechanism and if not what is needed.

**Comment by dgiormov** [comment]
Done, you can check it out here: https://istadevi024096trial.hanatrial.ondemand.com/#/
Login with google in order to work...
