### ISSUE TITLE
Color-coding for list-items / tracks and sessiondetails-view

### ISSUE THREAD

**Issue by panev** [dgiormov/ista.agenda.builder.web#11]
We need to add classes that reflect the location of the sessions to the list-items:

![image](https://cloud.githubusercontent.com/assets/3509489/4525610/9b32e9c4-4d55-11e4-92a2-dbf5e2464a71.png)

As well as the session-logistics container inside the sessiondetails view.

![image](https://cloud.githubusercontent.com/assets/3509489/4525634/e9ddcdd2-4d55-11e4-8889-c332c988d941.png)

I've already added track-1 manually to the markup for styling purposes, but you can remove it and add what/however you like.

Thanks!

**Comment by dgiormov** [comment]
fixed with latest commit 72ea1646d61de8ff49e736133efdbb737a4542fe

**Comment by panev** [comment]
@dgiormov The track classes inside the session details view are added, but they're track-a/b/c, while the ones added for for the list-items in the main view are track-1/2/3. Same goes for the actual strings. 

Should we make this consistent?
