### ISSUE TITLE
Comment like button

### ISSUE THREAD

**Issue by dgiormov** [dgiormov/ista.agenda.builder.web#13]
User should be able to like a comment, count of user likes should be visible.

**Comment by panev** [comment]
I'll add the markup for this, style it and then reassign it to someone else to do the functionality, if that's ok.

**Comment by panev** [comment]
I've added the like-widget markup: 

```
<div class="comment-like">
    <span>212</span>
    <i class="fa fa-thumbs-up"></i>
</div>
```

![image](https://cloud.githubusercontent.com/assets/3509489/4560231/6f520638-4ef3-11e4-8bb4-bc0471038b20.png)

When someone taps the like `comment-like`, the class `comment-like-liked` should be added, this  highlights the elements:

![image](https://cloud.githubusercontent.com/assets/3509489/4560196/2b1ecb36-4ef3-11e4-91de-1020ba8d894f.png)

I've also removed {{comment.likes}} from the badge that we used so there's no confusion.

**Comment by dgiormov** [comment]
I will enable the functionality

**Comment by dgiormov** [comment]
done
