### ISSUE TITLE
Welcome screen

### ISSUE THREAD

**Issue by panev** [dgiormov/ista.agenda.builder.web#19]
I've posted a mockup for the welcome screen here: 
https://groups.google.com/forum/#!topic/ista-agenda-builder/UI8okutNnAo

The scenario is: The user opens the app -> See's this screen until he hits the _OK_ button -> Enters Agenda list (main view).

I suppose the welcome messege itself and layout are up for debate, but we do need to have this screen with the logos, since it's a requirement.

I don't know how to go about implementation. I can help out with markup if you want.

Thoughts?

**Comment by dgiormov** [comment]
To Log in from this screen requires around 3 taps, isn't it better if we provide the possibility to log in from here?

**Comment by panev** [comment]
That's a good idea, we could do it. However there's two potential issues:

~~1. It would, potentially, limit the space for the sponsor logos, and they would have to be bellow the fold or smaller.~~ Scratch that, I think I have a solution.
1. Wouldn't that interfere with what we're talking about in #18? If we add a login would the welcome screen take longer to load or trip up the loading in the background? If I had to pick I'd say performance takes priority.

**Comment by dgiormov** [comment]
1. Agree, another concern is that the Login providers "logos" will appear side by side with the sponsors and I am not sure if this is ok. Maybe if we have a login button this could show the google, facebook etc. links?
2. No since logging is practically a redirect. But we should skip the page on the way back...

Also I am not sure if the page should be shown always, especially if user interaction is required to dismiss it.

**Comment by panev** [comment]
Sure! First visit only in my opinion. It's purpose is a "welcome" screen, after all.

Regarding the login prompt, this is an idea: 

![image](https://cloud.githubusercontent.com/assets/3509489/4629545/6538f790-53a5-11e4-858a-3a74d5e9c32a.png)

If the user clicks login, the modal dialog discussed in #22 is shown, if he clicks "not now", he just proceeds to the agenda. 

I'll discuss this with one of our UX people, but it seems ok, what do you think?

**Comment by dgiormov** [comment]
For me this is ok.

**Comment by panev** [comment]
UPDATE:
I've tried to add a basic welcome screen page which to style, but cannot. 

When I add a file to the root the grunt tasks do not trigger and there seems to be dependency issues.
I can't seem to add it as a view, either. I used codes.html as a base but to no avail.

@dgiormov @fen4o 
Can someone Please do the basic implementation of the welcome screen? I just need a blank html page, I'll add the markup and style it.

Thanks~

**Comment by fen4o** [comment]
I'll start working on it tomorrow.
Do you want to persist the "Not now" option? I can save it as a cookie, so subsequent requests won't show again.

**Comment by panev** [comment]
Yes, that'd be ideal. Users get prompted to login each time they perform an action that requires it, so it's unnecessary for the welcome screen to pop up each time. Just on the first visit. I can do localStorage.clear() for dev purposes.

Many thanks!

**Comment by fen4o** [comment]
Sorry for the delay - had some PC issues.
The feature is added in 14923ba80046b361f3d45ae2d7602b26c8aec4c6
You need to the content in the wellcomeModal element

**Comment by panev** [comment]
@fen4o Thanks! How would I go about showing the welcome screen again, after I've closed it? localStorage.clear() doesn't seem to work.

**Comment by fen4o** [comment]
Use this:
document.cookie ='hideWellcome=;expires=Thu, 01 Jan 1970 00:00:01 GMT;';

**Comment by panev** [comment]
I've styled the welcome screen modal for the mobile view, it currently looks like this:
![image](https://cloud.githubusercontent.com/assets/3509489/4903036/bb44e77c-643d-11e4-924f-427ca22a4144.png)
Please note, that the desktop version still hasn't been wroked on.

@fen4o @dgiormov 
I still need a separate login modal prompt for the welcome screen. Currently when you click login from the welcome dialog you see this: 
![image](https://cloud.githubusercontent.com/assets/3509489/4903093/0ffb06f2-643e-11e4-84dc-47fa6fd05dd3.png)

It closes the welcome screen and states that "you need to be logged in to do that", which doesn't make any sense.

Ideally, we need to have this happen when the user clicks "Log in" from the welcome screen:
![image](https://cloud.githubusercontent.com/assets/3509489/4903165/866dbd0c-643e-11e4-993b-afaecf9520ed.png)

We could do this by launching a new, separate modal, with just the social icons used to login, dedicated to the welcome screen.

Furthermore, are we going to have the welcome screen as a modal? Would it be possible for it to be a standalone view or html page? Please refer to #18

**Comment by dgiormov** [comment]
Committed: 938ef572a15472eab7c15bb76ecd8dea26837246 
Close if looks ok.

**Comment by panev** [comment]
Looks fine, I've styled the social icons and did responsive behaviour for the welcome screen.
