### ISSUE TITLE
Login tile

### ISSUE THREAD

**Issue by dgiormov** [dgiormov/ista.agenda.builder.web#22]
We need some sort of loggin tile or window or something, to show when the user clicks a button that requires that the user is logged in.

**Comment by panev** [comment]
We can create something like this:

![image](https://cloud.githubusercontent.com/assets/3509489/4629465/76c3f970-53a4-11e4-80a0-3a625130d2bc.png)

When the user clicks on an action, that requires him to be logged in, the this modal would appear. He could also close the modal if he would like.

I don't know how to go about implementing things, but for styling purposes I'd need a div with a paragraph inside. We could aslo just reuse the social icon styling we have in the menu.

Would this work?

**Comment by dgiormov** [comment]
Sure looks great

**Comment by panev** [comment]
I did some initial styling for this:

![image](https://cloud.githubusercontent.com/assets/3509489/4718295/a57e2cce-591f-11e4-851e-eab7ca5d74d8.png)

We still need to:
1. Replace Login/Not now buttons with the social icons
2. Make the modal appear in the other scenarios where login is needed (rating/commenting/adding a code, etc)

Thanks~
