### ISSUE TITLE
Login tile not showing up everywhere

### ISSUE THREAD

**Issue by panev** [dgiormov/ista.agenda.builder.web#23]
Currently, the login tile doesn't popup everywhere it needs to.

It needs to popup whenever a user is not logged an clicks on either of the following:
1. "add-session" mechanism in the main agenda view. ![image](https://cloud.githubusercontent.com/assets/3509489/4790917/35f1d9de-5dd7-11e4-88cf-c55c152e758b.png)
2. "My Agenda" button in main agenda view. ![image](https://cloud.githubusercontent.com/assets/3509489/4790953/95073306-5dd7-11e4-8ed8-892a5094f935.png)
3. Codes & Ranking page.
4. Rating ![image](https://cloud.githubusercontent.com/assets/3509489/4790938/62fa03ac-5dd7-11e4-922d-508162b3afad.png)
5. Commenting, whenever the user taps on the input filed. 
   ![image](https://cloud.githubusercontent.com/assets/3509489/4790946/7f4b6384-5dd7-11e4-940b-248cb90774eb.png)

**Comment by dgiormov** [comment]
Yep I know, I am working on generic fix

**Comment by dgiormov** [comment]
should be ok now, you can test it on the dev server
http://istadevi024096trial.hanatrial.ondemand.com
