### ISSUE TITLE
Codes and Ranking views merged into one

### ISSUE THREAD

**Issue by panev** [dgiormov/ista.agenda.builder.web#24]
Could we merge the two views into one? 

![image](https://cloud.githubusercontent.com/assets/3509489/4790982/02641d06-5dd8-11e4-9428-2d050f7d6866.png)

And move the header and input elements ontop of the ranking page?

![image](https://cloud.githubusercontent.com/assets/3509489/4791000/42e7f60e-5dd8-11e4-8bff-9ce759ebb1c4.png)

**Comment by dgiormov** [comment]
Sure we can:)

**Comment by dgiormov** [comment]
done, but it is a bit ugly (it is in ranking.html)
