### ISSUE TITLE
Back button in session details

### ISSUE THREAD

**Issue by panev** [dgiormov/ista.agenda.builder.web#26]
@fen4o I noticed you've added a back button in inside the session details, is there any particular reason for this? The location is a bit unconventional and it might confuse the user, furthermore it's quite close to the add-session button and might cause missclicks. 

If the idea of the button is to have a quick access back to the session list, I've added a home icon next to the logo, which points to that view anyway, that'll provide the user with the desired quick-link.

I think we should remove the back button, are you ok with this?

**Comment by dgiormov** [comment]
Yep we know. We want back button for a number of reasons, We can discuss it over the phone today.

P.S. the place that is now is purely by accident:)

**Comment by panev** [comment]
I've added a header-title element that contains the back buttom, however I still want to add a string to it saying "Back". I tried to do this in the backbutton.js file, however there's a jshint error thrown in grunt. @dgiormov @fen4o Can you add a <span>Back</span> inside the backbutton?

Thanks!

**Comment by panev** [comment]
I've styled the backbutton and header.

Thanks~
