### ISSUE TITLE
Add Player Status in leader board (user/gold/diamond)

### ISSUE THREAD

**Issue by dgiormov** [dgiormov/ista.agenda.builder.web#32]

**Comment by panev** [comment]
@dgiormov can we easily add classes to the first 10/20/50 people, respectively platinum/gold/silver or something, just so I have a better reference when doing the styling? By easily I mean a couple of minutes of work, if it's more it wouldn't be worth the hassle. 

Let me know, 
Thanks!

**Comment by dgiormov** [comment]
"rank0", "rank1", "rank2", "rank3" classes added. Higher number - more successful the player

**Comment by dgiormov** [comment]
should we close this one?

**Comment by panev** [comment]
not yet, I still need to polish up the rankings and icons

**Comment by panev** [comment]
I've made slight improvements, close if they look ok to you.
