### ISSUE TITLE
Show average rating in separate page or in session details page

### ISSUE THREAD

**Issue by dgiormov** [dgiormov/ista.agenda.builder.web#33]

**Comment by dgiormov** [comment]
I think we can close this one as well?

https://istadevi024096trial.hanatrial.ondemand.com/#/top

**Comment by panev** [comment]
I've just moved the stars in the name div so they're less visually obtrusive: 

![image](https://cloud.githubusercontent.com/assets/3509489/5175346/561635c6-7442-11e4-89ac-011204276a59.png)

Please review the changeset and close if all is well.
