### ISSUE TITLE
"My Agenda" view

### ISSUE THREAD

**Issue by panev** [dgiormov/ista.agenda.builder.web#5]
I've added an element in the main view that switches between the overall agenda and the user's personalized agenda:

![image](https://cloud.githubusercontent.com/assets/3509489/4478056/7d0882a0-4982-11e4-958a-8c3c2404a0cc.png)

Ideally we could implement swiping between the two.

I've used the panel-heading as a base. The class panel-link-active on the <a> needs to be added/removed when the views are switched.

Please let me know if you need anything styling/css wise.

Thanks!

**Comment by panev** [comment]
Also, these buttons: 

![image](https://cloud.githubusercontent.com/assets/3509489/4525496/760c83e0-4d54-11e4-91a9-de1bbdf485e0.png)

are used to add/remove sessions to "My Agenda". 

When the user taps them the session needs to be added to "My Agenda" and the following classes need to be changed in the main view, lines 10-12.

```
<div class="add-session not-added"> 
<!-- Classes need to be changed to "add-session session-added" when the session is added -->
    <i class="fa fa-plus"></i> 
    <!-- Classes need to be changed to "fa fa-check" when the session is added -->
</div>
```

Let me know if something is unclear.

Thanks!

**Comment by dgiormov** [comment]
Done, you can check it out here: https://istadevi024096trial.hanatrial.ondemand.com/#/
Login with google in order to work...

**Comment by panev** [comment]
Everything described above works great, however there are a few issues:
1. Since the "add session" button is inside the anchor tag, it is extremely difficult to click on a mobile device, and once you do you click the anchor tag as well and go inside the session. This is not ideal, I'm reopening this and assigning it to myself to make some markup changes that hopefully improve things.
2. If you aren't logged in it appears you can't add sessions to my agenda, thus the button is obsolete and confusing. @dgiormov We should either hide it when the user is logged out or make adding sessions available when the user is logged out trough local storage, what do you think?

**Comment by fen4o** [comment]
The clicking issue is fixed in cea3ccc972599495c5ae60e8393b4ab1ce1d8017

**Comment by fen4o** [comment]
I suggest that clicking will prompt the user to log on.

**Comment by dgiormov** [comment]
Prompting the user to log in seems the right approach for me. This action will be distributed on a number of actions like rating, commenting and so on...

**Comment by panev** [comment]
@fen4o @dgiormov Sounds very reasonable, lets do it

I've made some markup changes, pretty much wrapped the anchor tag inside a div and moved the classes and made the add button and track label outside of it. The reason behind this is that eventually we'd like to make track# go to the venue map, as well as improve the tapping for the add-session button. It's also more semantic :-)

Everything seems to work, however please review the commit and see if there's potential issues with the markup changes.

Thanks!
