### ISSUE TITLE
Adding a class on the first <li> in the leader board 

### ISSUE THREAD

**Issue by panev** [dgiormov/ista.agenda.builder.web#6]
I need a class added in the first list-group-item in the leaderboard, in the ranking view. Something like "list-group-leader". This way I can style that tile appropriately.

Also, if possible, we could change <i class="fa fa-user"> to <i class="fa fa-trophy">, just for the first element. This way the leader would get a cup as an icon to attribute to the first-place styling, motivating users to earn more points :-)

Many thanks!

**Comment by dgiormov** [comment]
You should have leader class added to the first entry
