### ISSUE TITLE
collapse / expand behaviour on the session description

### ISSUE THREAD

**Issue by panev** [dgiormov/ista.agenda.builder.web#7]
I've added two classes that style the description to be expanded or collapsed. 

The class `description-collapsed` is present in the `session-description` div, so the description is collapsed by default. 

When the user taps `session-overall`(the parent container), the class `description-collapsed` needs to be switched with `description-expanded`. This will expand the description, respectively when the user taps again, the classes need to be switched back so the description is collapsed.

Thanks!

**Comment by dgiormov** [comment]
fixed, reopen if issues occur.
