### ISSUE TITLE
Codes title text

### ISSUE THREAD

**Issue by panev** [dgiormov/ista.agenda.builder.web#8]
In the codes view, the title text says "4 letter reward codes can be won from various activities. Enter the code here to activate it. **Please be careful, we don’t allow many “mistakes”**"

What do we mean by not allowing many mistakes? How much mistakes do we allow?
What does quantifies as a mistake?
What happens when the users makes a mistake?

Can someone elaborate on this? I think we can present this better and aid the user in not making mistakes.

Thanks!

**Comment by dgiormov** [comment]
The idea here is that some people may try to guess a code so they can get some "free" points. We have placed a logic that after a user tries to put 10 wrong codes, he/she will be banned to add new codes.

Mistake is adding a code that does not exist - certain codes will be prepared and added to our application, only these codes will give points.

Currently if a user makes a mistake, an error dialog appears stating that this code in "wrong" and the user has XX number of  wrong code attempts.

**Comment by panev** [comment]
Great, this clarifies things. I think it would perhaps be better to move "Please be careful, we don’t allow many “mistakes” inside the error dialog, since not every user would try to cheat, and the message is directed at those who do.

Also we could add examples in brakes after the word "activity" to hint to users where they could get points from:
"4 letter reward codes can be won from various activities (going to booths, listening carefully at lectures, something else) "

What do you think?

**Comment by dgiormov** [comment]
sounds good

**Comment by panev** [comment]
I've edited the text. Please close this issue after you've added the "please be careful" bit to the error message. 

By the way, if the codes are by any chance case-sensitive, we should indicate that, too.

Thanks!

**Comment by dgiormov** [comment]
no the codes are not case sensitive, closing the issue
